[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]
solc-version = "0.8.17"
optimizer = true
optimizer-runs = 10_000_000

[rpc_endpoints]
hyperspace = "${HYPERSPACE_RPC_URL}"

