name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: ["cli/**", ".github/workflows/cli.yml"]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    env:
      TEST_RPC_URL: ${{secrets.TEST_RPC_URL}}
      TEST_MNEMONIC: ${{secrets.TEST_MNEMONIC}}
      TEST_FACTORY_ADDRESS: ${{secrets.TEST_FACTORY_ADDRESS}}
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-03
          override: true
          components: rustfmt, clippy
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install OpenCL
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev
      - name: Build
        run: |
          cd cli
          cargo build -vv
      - name: Run tests
        run: |
          cd cli
          cargo test cli  -- --nocapture --test-threads 1
