name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: ["cli/**",".github/workflows/cli.yml"]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd cli
        cargo build --verbose
    - name: Run tests
      run: |
        cd cli
        cargo test cli  -- --nocapture --test-threads 1 --verbose