name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: ["src/**", "test/**/**"]
  workflow_dispatch:

jobs:
  test:
    name: Contract-Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install node modules
        uses: actions/setup-node@v3
        run: |
          cd lib/filecoin-solidity
          npm install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install solc-select
        run: |
          pip3 install solc-select

      - name: Compile
        run: |
          forge build --build-info
          solc-select install 0.8.16
          solc-select use 0.8.16

      - name: Run forge tests
        run: forge test -vvv

      - name: Patch foundry
        run: rm foundry.toml

      - name: Run Slither
        uses: crytic/slither-action@v0.2.0
        id: slither
        with:
          target: "src/PayoutFactory.sol"
          fail-on: none

      - name: Echidna Tests on PaymentSplitter
        uses: crytic/echidna-action@v2
        env:
          SOLC_VERSION: 0.8.16
        with:
          solc-version: 0.8.16
          files: test/echidna/PaymentSplitterTest.sol
          contract: TestPaymentSplitter
          crytic-args: --ignore-compile

      - name: Echidna Tests on PayoutFactory
        uses: crytic/echidna-action@v2
        env:
          SOLC_VERSION: 0.8.16
        with:
          solc-version: 0.8.16
          files: test/echidna/PayoutFactoryTest.sol
          contract: TestPayoutFactory
          crytic-args: --ignore-compile

      - name: Echidna Tests on Evaluator
        uses: crytic/echidna-action@v2
        env:
          SOLC_VERSION: 0.8.16
        with:
          solc-version: 0.8.16
          files: test/echidna/EvaluatorTest.sol
          contract: TestEvaluator
          crytic-args: --ignore-compile
