name: Echidna Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  test:
    name: Contract-Tests
    env:
      SOLC_VERSION: 0.8.13   
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install solc-select
      run: |
        pip3 install solc-select
    - name: Compile
      run: |
        forge build --build-info
        solc-select install 0.8.13    
        solc-select use 0.8.13
    - name: Run tests
      run: forge test -vvv

    - name: Run Echidna
      uses: crytic/echidna-action@v2
      with:
        solc-version: 0.8.13
        files: test/echidna
        contract: TestPaymentSplitter
        crytic-args: --ignore-compile